spring:
  redis:
    host: 127.0.0.1
    password: 123456
    port: 6379
    jedis:
      pool:
        min-idle: 0
        max-active: 8
        max-idle: 8
        max-wait: 5000
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hyj?characterEncoding=UTF-8&amp;allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  configuration:
    cache-enabled: true
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8090